broadcast:
  pre: '&9Cохраняем сервер'
  post: '&9Сохранение завершено'
broadcastbackup:
  pre: '&9Делаем бэкап'
  post: '&9Автобэкап сделан'
autorestart:
  restarting: '&9Сервер перезагружается'
  countdown: '&9Сервер перезагрузится через {SECONDS} секунд'
insufficentpermissions: '&9У вас нет доступа к этой команде'
