broadcast:
  pre: '&9AutoSaving'
  post: '&9AutoSave Complete'
broadcastbackup:
  pre: '&9AutoBackuping'
  post: '&9AutoBackup Complete'
autorestart:
  restarting: '&9Server is restarting'
  countdown: '&9Server will restart in {SECONDS} seconds'
insufficentpermissions: '&cYou do not have access to that command.'
